name: byte_extensions
description: Extensions for handling common types and converting them to/from byte arrays
version: 0.0.3
homepage:
repository: https://github.com/flutter-institute/byte_extensions
issue_tracker: https://github.com/flutter-institute/byte_extensions/issues

environment:
  sdk: '>=2.18.1 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
